# Generated by Django 5.0.1 on 2024-02-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.UUIDField()),
                ('file_id', models.UUIDField()),
                ('file_name', models.CharField(default='unnamed', max_length=255)),
            ],
        ),
    ]
