# Generated by Django 5.0.1 on 2024-02-01 03:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_id',
            field=models.UUIDField(default=uuid.UUID('669a9702-f41a-4f28-b673-5a3e91a738c6')),
        ),
    ]
