# Generated by Django 5.0.1 on 2024-02-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_uploadedfile_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_id',
            field=models.UUIDField(),
        ),
    ]
